<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DoctorRegisterController extends Controller
{
    public function index()
    {
        $nationalities = [
            "Afghan",
            "Albanian",
            "Algerian",
            "American",
            "Andorran",
            "Angolan",
            "Antiguan",
            "Argentine",
            "Armenian",
            "Australian",
            "Austrian",
            "Azerbaijani",
            "Bahamian",
            "Bahraini",
            "Bangladeshi",
            "Barbadian",
            "Belarusian",
            "Belgian",
            "Belizean",
            "Beninese",
            "Bhutanese",
            "Bolivian",
            "Bosnian",
            "Botswanan",
            "Brazilian",
            "British",
            "Bruneian",
            "Bulgarian",
            "Burkinabe",
            "Burmese",
            "Burundian",
            "Cambodian",
            "Cameroonian",
            "Canadian",
            "Cape Verdean",
            "Central African",
            "Chadian",
            "Chilean",
            "Chinese",
            "Colombian",
            "Comoran",
            "Congolese (Congo-Brazzaville)",
            "Congolese (Congo-Kinshasa)",
            "Costa Rican",
            "Croatian",
            "Cuban",
            "Cypriot",
            "Czech",
            "Danish",
            "Djiboutian",
            "Dominican (Dominica)",
            "Dominican (Dominican Republic)",
            "Dutch",
            "East Timorese",
            "Ecuadorean",
            "Egyptian",
            "Emirati",
            "English",
            "Equatorial Guinean",
            "Eritrean",
            "Estonian",
            "Ethiopian",
            "Fijian",
            "Finnish",
            "French",
            "Gabonese",
            "Gambian",
            "Georgian",
            "German",
            "Ghanaian",
            "Greek",
            "Grenadian",
            "Guatemalan",
            "Guinean",
            "Bissau-Guinean",
            "Guyanese",
            "Haitian",
            "Honduran",
            "Hungarian",
            "Icelandic",
            "Indian",
            "Indonesian",
            "Iranian",
            "Iraqi",
            "Irish",
            "Israeli",
            "Italian",
            "Ivorian",
            "Jamaican",
            "Japanese",
            "Jordanian",
            "Kazakh",
            "Kenyan",
            "Kiribati",
            "Korean (North)",
            "Korean (South)",
            "Kosovar",
            "Kuwaiti",
            "Kyrgyz",
            "Lao",
            "Latvian",
            "Lebanese",
            "Liberian",
            "Libyan",
            "Liechtensteiner",
            "Lithuanian",
            "Luxembourgish",
            "Macedonian",
            "Malagasy",
            "Malawian",
            "Malaysian",
            "Maldivian",
            "Malian",
            "Maltese",
            "Marshallese",
            "Mauritanian",
            "Mauritian",
            "Mexican",
            "Micronesian",
            "Moldovan",
            "Monacan",
            "Mongolian",
            "Montenegrin",
            "Moroccan",
            "Mozambican",
            "Namibian",
            "Nauruan",
            "Nepalese",
            "New Zealander",
            "Nicaraguan",
            "Nigerien",
            "Nigerian",
            "Norwegian",
            "Omani",
            "Pakistani",
            "Palauan",
            "Palestinian",
            "Panamanian",
            "Papua New Guinean",
            "Paraguayan",
            "Peruvian",
            "Philippine",
            "Polish",
            "Portuguese",
            "Qatari",
            "Romanian",
            "Russian",
            "Rwandan",
            "Saint Lucian",
            "Salvadoran",
            "Samoan",
            "San Marinese",
            "Sao Tomean",
            "Saudi",
            "Scottish",
            "Senegalese",
            "Serbian",
            "Seychellois",
            "Sierra Leonean",
            "Singaporean",
            "Slovak",
            "Slovene",
            "Solomon Islander",
            "Somali",
            "South African",
            "South Sudanese",
            "Spanish",
            "Sri Lankan",
            "Sudanese",
            "Surinamese",
            "Swazi",
            "Swedish",
            "Swiss",
            "Syrian",
            "Taiwanese",
            "Tajik",
            "Tanzanian",
            "Thai",
            "Togolese",
            "Tongan",
            "Trinidadian",
            "Tunisian",
            "Turkish",
            "Turkmen",
            "Tuvaluan",
            "Ugandan",
            "Ukrainian",
            "Uruguayan",
            "Uzbek",
            "Vanuatuan",
            "Vatican citizen",
            "Venezuelan",
            "Vietnamese",
            "Welsh",
            "Yemeni",
            "Zambian",
            "Zimbabwean"
        ];
        $countries = [
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo (Congo-Brazzaville)",
            "Congo (Democratic Republic)",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Ivory Coast",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "North Korea",
            "North Macedonia",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Korea",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Togo",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Zambia",
            "Zimbabwe"
        ];

        $specializations = [
            "Allergy and Immunology",
            "Dentist",
            "Anesthesiology",
            "Cardiology",
            "Nutrition & Dietetics",
            "Dermatology",
            "Emergency Medicine",
            "Endocrinology",
            "Family Medicine",
            "Gastroenterology",
            "General Surgery",
            "Behavioral & Mental Health",
            "Rehabilitation",
            "Geriatric Medicine",
            "Hematology",
            "Infectious Disease",
            "Internal Medicine",
            "Medical Genetics",
            "Neonatology",
            "Nephrology",
            "Neurology",
            "Neurosurgery",
            "Obstetrics and Gynecology (OB/GYN)",
            "Occupational Medicine",
            "Oncology",
            "Ophthalmology",
            "Orthopedic Surgery",
            "Otolaryngology (ENT)",
            "Pain Management",
            "Pathology",
            "Pediatrics",
            "Physical Medicine and Rehabilitation (PM&R)",
            "Plastic Surgery",
            "Podiatry",
            "Psychiatry",
            "Pulmonology",
            "Pharmacist",
            "Aesthetics",
            "Radiology",
            "Rheumatology",
            "Sports Medicine",
            "Urology",
            "Vascular Surgery",
            "Adolescent Medicine",
            "Aerospace Medicine",
            "Bariatric Surgery",
            "Cardiac Electrophysiology",
            "Clinical Pharmacology",
            "Colorectal Surgery",
            "Critical Care Medicine",
            "Cytopathology",
            "Dermatopathology",
            "Developmental-Behavioral Pediatrics",
            "Electrophysiology",
            "Facial Plastic Surgery",
            "Forensic Pathology",
            "Hand Surgery",
            "Hospice and Palliative Medicine",
            "Immunology",
            "Interventional Cardiology",
            "Interventional Radiology",
            "Maternal-Fetal Medicine",
            "Micrographic Surgery",
            "Molecular Genetic Pathology",
            "Musculoskeletal Radiology",
            "Neonatal-Perinatal Medicine",
            "Neurodevelopmental Disabilities",
            "Neuroradiology",
            "Nuclear Medicine",
            "Ophthalmic Pathology",
            "Oral and Maxillofacial Surgery",
            "Orthopedic Sports Medicine",
            "Otorhinolaryngology - Head and Neck Surgery",
            "Pain Medicine",
            "Pediatric Cardiology",
            "Pediatric Endocrinology",
            "Pediatric Gastroenterology",
            "Pediatric Hematology-Oncology",
            "Pediatric Nephrology",
            "Pediatric Neurology",
            "Pediatric Pulmonology",
            "Pediatric Radiology",
            "Pediatric Surgery",
            "Perinatology",
            "Phlebology",
            "Plastic and Reconstructive Surgery",
            "Preventive Medicine",
            "Psychosomatic Medicine",
            "Radiation Oncology",
            "Reproductive Endocrinology and Infertility",
            "Sleep Medicine",
            "Transplant Hepatology",
            "Trauma Surgery",
        ];

        $subSpecializations = [
            "Pediatric Allergy and Immunology",
            "Clinical Pharmacist",
            "Advance Nurse Practitioner",
            "Adult Allergy and Immunology",
            "Cardiothoracic Anesthesiology",
            "Neuroanesthesiology",
            "Obstetric Anesthesiology",
            "Pediatric Anesthesiology",
            "Pain Management",
            "Regional Anesthesia",
            "Physiotherapist",
            "Chiropractor",
            "Interventional Cardiology",
            "Electrophysiology",
            "Heart Failure and Transplant Cardiology",
            "Preventive Cardiology",
            "Echocardiography",
            "Pediatric Dermatology",
            "Dermatopathology",
            "Mohs Surgery",
            "Cosmetic Dermatology",
            "Pediatric Emergency Medicine",
            "Critical Care Medicine",
            "Toxicology",
            "Sports Medicine",
            "Diabetology",
            "Reproductive Endocrinology",
            "Thyroidology",
            "Endocrine Oncology",
            "Geriatrics",
            "Women's Health",
            "Hepatology",
            "Interventional Gastroenterology",
            "Inflammatory Bowel Disease",
            "Colorectal Surgery",
            "Breast Surgery",
            "Trauma Surgery",
            "Surgical Oncology",
            "Minimally Invasive Surgery",
            "Palliative Care",
            "Hematologic Oncology",
            "Transfusion Medicine",
            "HIV/AIDS",
            "Tropical Medicine",
            "Hospital Medicine",
            "Primary Care",
            "Clinical Genetics",
            "Cytogenetics",
            "Neonatal-Perinatal Medicine",
            "Transplant Nephrology",
            "Multiple Sclerosis",
            "Epilepsy",
            "Movement Disorders (Parkinson's, etc.)",
            "Stroke",
            "Neuromuscular Disorders",
            "Spine Surgery",
            "Cranial Surgery",
            "Neurovascular Surgery",
            "Maternal-Fetal Medicine",
            "Reproductive Endocrinology and Infertility",
            "Gynecologic Oncology",
            "Urogynecology",
            "Environmental Medicine",
            "Medical Oncology",
            "Radiation Oncology",
            "Retina",
            "Glaucoma",
            "Cornea",
            "Cataracts",
            "Pediatric Ophthalmology",
            "Hand Surgery",
            "Foot and Ankle Surgery",
            "Joint Replacement",
            "Otology/Neurotology",
            "Rhinology/Sinus Surgery",
            "Laryngology",
            "Pediatric Otolaryngology",
            "Head and Neck Surgery",
            "Interventional Pain Management",
            "Anatomic Pathology",
            "Clinical Pathology",
            "Forensic Pathology",
            "Cytopathology",
            "Pediatric Cardiology",
            "Pediatric Endocrinology",
            "Pediatric Gastroenterology",
            "Pediatric Hematology-Oncology",
            "Pediatric Nephrology",
            "Pediatric Neurology",
            "Pediatric Pulmonology",
            "Pediatric Rheumatology",
            "Neonatology",
            "Spinal Cord Injury Medicine",
            "Brain Injury Medicine",
            "Craniofacial Surgery",
            "Aesthetic Surgery",
            "Aesthetician",
            "Reconstructive Surgery",
            "Child and Adolescent Psychiatry",
            "Geriatric Psychiatry",
            "Addiction Psychiatry",
            "Sleep Medicine",
            "Clinical Psychologists",
            "Counselor",
            "Behavioral Therapist",
            "Art/Music Therapist",
            "Interventional Pulmonology",
            "Physical Therapist",
            "Interventional Radiology",
            "Occupational Therapists (OTs)",
            "Speech-Language Pathologists (SLPs)",
            "Audiologists",
            "Orthotists and Prosthetists",
            "Recreational Therapists",
            "Neuroradiology",
            "Musculoskeletal Radiology",
            "Pediatric Radiology",
            "Breast Imaging",
            "Pediatric Urology",
            "Urologic Oncology",
            "Andrology",
            "Endovascular Surgery",
            "Orthodontist",
            "Periodontist"
        ];

        return view("doctors.register", compact('nationalities', 'countries', 'specializations', 'subSpecializations'));
    }

    public function store(Request $request)
    {
        // Validate the form data
        $validatedData = $request->validate([
            'salutation' => 'required|string|max:10',
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'gender' => 'required|in:male,female,prefer-not-to-say',
            'nationality' => 'required|string|max:255',
            'email' => 'required|email|unique:doctors,email',
            'phone' => 'required|string|max:20',

            // Address fields
            'address' => 'required|string|max:255',
            'address_2' => 'nullable|string|max:255',
            'city' => 'required|string|max:255',
            'state' => 'required|string|max:255',
            'postal' => 'required|string|max:20',
            'country' => 'required|string|max:255',

            // Professional Information
            'medical_license_number' => 'required|string|max:255',
            'medical_license_authority' => 'required|string|max:255',
            'medical_license_country' => 'required|string|max:255',
            'specialization' => 'required|string|max:255',
            'sub_specialization' => 'required|string|max:255',
            'experience' => 'required|numeric|min:0',

            // Current Workspace
            'clinic_name' => 'required|string|max:255',
            'clinic_address' => 'required|string|max:255',
            'clinic_address_2' => 'nullable|string|max:255',
            'clinic_city' => 'required|string|max:255',
            'clinic_state' => 'required|string|max:255',
            'clinic_postal' => 'required|string|max:20',
            'clinic_country' => 'required|string|max:255',
            'position' => 'required|string|max:255',

            // Educational Details
            'degree' => 'required|string|max:255',
            'school_or_college' => 'required|string|max:255',
            'date_of_graduation' => 'required|date',
            'additional_certifications' => 'nullable|string',
            'continuing_medical_education' => 'nullable|string|max:255',

            // Professional Affiliations
            'membership_in_medical_associations' => 'nullable|string',
            'licensing_bodies' => 'nullable|string',

            // International Practice
            'willing_to_international_patients' => 'required|in:yes,no,prefer-not-to-say',
            'preferred_patient_countries' => 'nullable|string',
            'preferred_communication' => 'required|array',
            'virtual_consultations' => 'required|in:yes,no',
            'second_opinions' => 'required|in:yes,no',
            'treatments_list' => 'required|string',
            'estimated_cost' => 'required|string',
            'international_insurance' => 'required|in:yes,no',
            'payment_methods' => 'required|array',

            // Document Uploads
            'medical_license' => 'required|file|mimes:pdf,doc,docx,txt|max:2048',
            'degree_certificates' => 'required|array',
            'degree_certificates.*' => 'file|mimes:pdf,doc,docx,txt|max:2048',
            'certifications' => 'required|file|mimes:pdf,doc,docx,txt|max:2048',
            'resume' => 'required|file|mimes:pdf,doc,docx,txt|max:2048',
            'profile_picture' => 'required|image|mimes:jpeg,png,jpg|max:2048',

            // Terms and Signature
            'terms_and_conditions' => 'required|accepted',
            'signature' => 'required|string' // Base64 encoded signature data
        ]);

        try {
            // Handle file uploads
            $medicalLicensePath = $request->file('medical_license')->store('documents/licenses', 'public');

            $degreeCertificatePaths = [];
            foreach ($request->file('degree_certificates') as $certificate) {
                $degreeCertificatePaths[] = $certificate->store('documents/certificates', 'public');
            }

            $certificationsPath = $request->file('certifications')->store('documents/certifications', 'public');
            $resumePath = $request->file('resume')->store('documents/resumes', 'public');
            $profilePicturePath = $request->file('profile_picture')->store('images/profiles', 'public');

            // Create doctor record in database
            // $doctor = Doctor::create([
            //     'salutation' => $validatedData['salutation'],
            //     'first_name' => $validatedData['first_name'],
            //     'last_name' => $validatedData['last_name'],
            //     'gender' => $validatedData['gender'],
            //     'nationality' => $validatedData['nationality'],
            //     'email' => $validatedData['email'],
            //     'phone' => $validatedData['phone'],

            //     // Add all other fields...

            //     'medical_license_path' => $medicalLicensePath,
            //     'degree_certificates' => json_encode($degreeCertificatePaths),
            //     'certifications_path' => $certificationsPath,
            //     'resume_path' => $resumePath,
            //     'profile_picture' => $profilePicturePath,

            //     'signature' => $validatedData['signature']
            // ]);

            return response()->json([
                'status' => 'success',
                'message' => 'Doctor registration successful',
                // 'data' => $doctor
            ], 201);

        } catch (\Exception $e) {
            return response()->json([
                'status' => 'error',
                'message' => 'Registration failed: ' . $e->getMessage()
            ], 500);
        }
    }
}
